#!/usr/bin/env python

import sys
import accolite

# Usage function
def usage(stream):
    stream.write("Usage: accolite-cmds [Options]\n")
    stream.write("Options:\n")
    stream.write("--help, -h                  : \t This help message.\n")

def main():
    commands = sorted(accolite.availableCommands())
    for cmd in commands:
        sys.stdout.write(cmd + "\n")

if __name__ == '__main__':
    sys.exit(main())
