#!/usr/bin/env python

import sys
import accolite

# Usage function
def usage(stream):
    stream.write("Usage: accolite-install-dir [Options]\n")
    stream.write("Options:\n")
    stream.write("--help, -h                  : \t This help message.\n")

def main():
    sys.stdout.write(accolite.installDir() + "\n")

if __name__ == '__main__':
    sys.exit(main())
