#!/usr/bin/env python
#
# Copyright (c) 2012 Casati Romain
# All rights reserved.
#
# This file is part of Accolite.
#
# Accolite is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Accolite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Accolite.  If not, see <http://www.gnu.org/licenses/>


import sys
import accolite

# Usage function
def usage(stream):
    stream.write("Usage: accolite-bash-completion [Options]\n")
    stream.write("Options:\n")
    stream.write("--help, -h                  : \t This help message.\n")

def main():
    sys.stdout.write("Assuming you are using bash.\n\
To enable bash completion for accolite, just create\n\
a file named .bash_completions in your home (~/) and put\n\
in it the folowing lines:\n\
    if $(command -v accolite-install-dir >/dev/null 2>&1)\\\n\
       && [ -f $(accolite-install-dir)/accolite_bash_completion ]; then\n\
        . $(accolite-install-dir)/accolite_bash_completion\n\
    fi\n\
Then add at the end of your .bashrc the folowing lines:\n\
    if [ -f ~/.bash_completions ]; then\n\
        . ~/.bash_completions\n\
    fi\n\
The completion will start once .bashrc will be sourced.\n")

if __name__ == '__main__':
    sys.exit(main())
