#!/usr/bin/env python

import sys
import os
import multiprocessing
import subprocess
import accolite

# Usage function
def usage(stream):
    stream.write("Usage: accolite-compile [Options]\n")
    stream.write("Options:\n")
    stream.write("--help, -h             : \t This help message.\n")
    stream.write("--build-type, -b <type>: \t Specify a build type in Release RelWithDebInfo Debug DebugFull. Default is Release.\n")
    stream.write("--cmake-args, -c <args>: \t Specify arguments to pass to cmake. Default is \"-DCMAKE_BUILD_TYPE=<type-passed-to-b-option>\"\n")
    stream.write("--make-args, -m <args> : \t Specify arguments to pass to make. Default is \"-j<number-of-core+1> install\".\n")


def main():
    # Preset options
    buildtype = "Release"
    cmakeargs = []
    makeargs = []
    # Get options
    argv = sys.argv[1:]
    while len(argv) > 0 and argv[0].startswith("-"):
        if argv[0] in ["--help","-h"]:
            usage(sys.stdout)
            return 0
        elif argv[0] in ["--build-type","-b"]:
            argv = argv[1:]
            buildtype = argv[0]
        elif argv[0] in ["--cmake-args","-c"]:
            argv = argv[1:]
            cmakeargs.append(argv[0])
        elif argv[0] in ["--make-args","-m"]:
            argv = argv[1:]
            makeargs.append(argv[0])
        else:
            sys.stderr.write("Unknown option " + argv[0] + "!")
            usage(sys.stderr)
            return 1
        # Shift argument
        argv = argv[1:]

    # Set build type
    cmakeargs.insert(0,"-DCMAKE_BUILD_TYPE=" + buildtype)
    # Get nbthreads +1
    makeargs.insert(0, "-j" + str(multiprocessing.cpu_count()+1))
    # Install lib
    makeargs.append("install")

    # Get working dir    
    if accolite.workingdir() == "":
        sys.stderr.write("It seems that you are not in a working accolite project!\n")
        return 1
    builddir = accolite.absdir("build")
    bindir = accolite.absdir("bin")
    tmpdir = accolite.absdir("tmp")
    cmakedir = accolite.absdir("cmake")

    if not os.path.exists(builddir):
        os.makedirs(builddir)
    if not os.path.exists(bindir):
        os.makedirs(bindir)
    if not os.path.exists(tmpdir):
        os.makedirs(tmpdir)

    # Set lasts arguments
    cmakeargs.insert(0, "cmake")
    cmakeargs.append(cmakedir)
    makeargs.insert(0, "make")
    sys.stdout.write("Runing cmake inside " + builddir + "\n")
    if subprocess.Popen(cmakeargs, cwd=builddir).wait() == 0:
        sys.stdout.write("Runing make\n")
        return subprocess.Popen(makeargs, cwd=builddir).wait()
    else:
        return 3


if __name__ == '__main__':
    sys.exit(main())
