#!/usr/bin/env python

import sys
import os
import accolite

# Usage function
def usage(stream):
    stream.write("Usage: accolite-init [Options] <working dir>\n")
    stream.write("Options:\n")
    stream.write("--help, -h                  : \t This help message.\n")
    stream.write("--config-file, -c <xml file>: \t Give a configuration file for initialize the project.\n")


def main():
    # Preset options
    configfile = ""
    # Get options
    argv = sys.argv[1:]
    while len(argv) > 0 and argv[0].startswith("-"):
        if argv[0] in ["--help","-h"]:
            usage(sys.stdout)
            return 0
        elif argv[0] in ["--config-file","-c"]:
            argv = argv[1:]
            configfile = argv[0]
        else:
            sys.stderr.write("Unknown option " + argv[0] + "!")
            usage(sys.stderr)
            return 1
        # Shift argument
        argv = argv[1:]

    if len(argv) == 0:
        sys.stderr.write("Mandatory argument <working dir> not found.\n")
        usage(sys.stderr)
        return 1

    # Set dirs
    rootdir = argv[0]
    accolitedir = os.path.abspath(os.path.join(rootdir, ".accolite"))
    os.makedirs(accolitedir)
    # Project name
    projectname = os.path.basename(os.path.abspath(rootdir))
    # Put the config file inside .accolite
    if configfile == "":
        configxml = accolite.defaultxml(projectname)
    else:
        configxml = parse(configfile)
    configxmlfile = open(os.path.abspath(os.path.join(accolitedir, "config.xml")), 'w')
    configxml.writexml(configxmlfile)
    configxmlfile.close()

    # Go inside working dir
    os.chdir(rootdir)

    # Creates dirsr
    for directory in ["tests","cmake","src","examples","doc"]:
        if accolite.relativedir(directory) != "":
            os.makedirs(accolite.absdir(directory))
    
    cmakedir = accolite.absdir("cmake")
    testsdir = accolite.absdir("tests")

    # Populating tests dir
    for filename in ["TestRunner.h","ExampleTest.cpp"]:
        filecurr = open(os.path.abspath(os.path.join(testsdir, filename)), 'w')
        filecurr.write(accolite.stringfile(filename))
        filecurr.close()

    # Populating cmakedir
    for filename in ["valgrind.supp","PathsDefinitions.cmake","ExamplesLinks.cmake","CMakeExamplesLists.cmake","CTestConfig.cmake","CTestDashboard.cmake","CMakeLists.txt","CMakeTestsLists.cmake","TestsLinks.cmake","Dependencies.cmake"]:
        filecurr = open(os.path.abspath(os.path.join(cmakedir, filename)), 'w')
        filecurr.write(accolite.stringfile(filename))
        filecurr.close()


if __name__ == '__main__':
    sys.exit(main())
