#!/usr/bin/env python

import sys
import os.path
import shutil

# Usage function
def usage(stream):
    stream.write("Usage: accolite-clean\n")

# Get working project dir
def workingdir():
    prevpath = ""
    currentpath = os.path.abspath(os.path.curdir)
    while not ( os.path.isdir(os.path.join(currentpath, ".accolite")) or currentpath == prevpath ):
        prevpath = currentpath
        currentpath = os.path.abspath(os.path.join(currentpath, os.path.pardir))
    if currentpath == prevpath and not os.path.isdir(os.path.join(currentpath, ".accolite")):
        return ""
    return currentpath
    

if __name__ == "__main__":
    rootdir = workingdir()
    if rootdir == "":
        sys.stderr.write("It seems that you are not in a working accolite project!\n")
        exit(1)
    builddir = os.path.abspath(os.path.join(rootdir, "build"))
    bindir = os.path.abspath(os.path.join(rootdir, "bin"))
    tmpdir = os.path.abspath(os.path.join(rootdir, "tmp"))
    if os.path.isdir(builddir):
        sys.stdout.write("Deleting " + builddir + "... ");
        shutil.rmtree(builddir)
        sys.stdout.write("Done.\n");
    if os.path.isdir(bindir):
        sys.stdout.write("Deleting " + bindir + "... ");
        shutil.rmtree(bindir)
        sys.stdout.write("Done.\n");
    if os.path.isdir(tmpdir):
        sys.stdout.write("Deleting " + tmpdir + "... ");
        shutil.rmtree(tmpdir)
        sys.stdout.write("Done.\n");
    
