#!/usr/bin/env python

import sys
import os.path
import shutil
import accolite

# Usage function
def usage(stream):
    stream.write("Usage: accolite-clean\n")
    

if __name__ == "__main__":
    rootdir = accolite.workingdir()
    if rootdir == "":
        sys.stderr.write("It seems that you are not in a working accolite project!\n")
        exit(1)
    builddir = accolite.absbuilddir()
    bindir = accolite.absbindir()
    tmpdir = accolite.abstmpdir()
    if os.path.isdir(builddir):
        sys.stdout.write("Deleting " + builddir + "... ");
        shutil.rmtree(builddir)
        sys.stdout.write("Done.\n");
    if os.path.isdir(bindir):
        sys.stdout.write("Deleting " + bindir + "... ");
        shutil.rmtree(bindir)
        sys.stdout.write("Done.\n");
    if os.path.isdir(tmpdir):
        sys.stdout.write("Deleting " + tmpdir + "... ");
        shutil.rmtree(tmpdir)
        sys.stdout.write("Done.\n");
    
