#!/usr/bin/env python

import sys
import accolite

# Usage function
def usage(stream):
    stream.write("Usage: accolite-bash-completion [Options]\n")
    stream.write("Options:\n")
    stream.write("--help, -h                  : \t This help message.\n")

def main():
    sys.stdout.write("Assuming you are using bash.\n\
To enable bash completion for accolite, just create\n\
a file named .bash_completions in your home (~/) and put\n\
in it the folowing lines:\n\
    if $(command -v accolite-install-dir >/dev/null 2>&1)\\\n\
       && [ -f $(accolite-install-dir)/accolite_bash_completion ]; then\n\
        . $(accolite-install-dir)/accolite_bash_completion\n\
    fi\n\
Then add at the end of your .bashrc the folowing lines:\n\
    if [ -f ~/.bash_completions ]; then\n\
        . ~/.bash_completions\n\
    fi\n\
The completion will start once .bashrc will be sourced.\n")

if __name__ == '__main__':
    sys.exit(main())
