#!/usr/bin/env python

import sys
import accolite

# Usage function
def usage(stream):
    stream.write("Usage: accolite-root [Options]\n")
    stream.write("Options:\n")
    stream.write("--help, -h                  : \t This help message.\n")

def main():
    wdir = accolite.workingDir()
    if wdir == "":
        sys.stderr.write("It seems that you are not in a working accolite project!\n")
        return 1
    sys.stdout.write(wdir + "\n")

if __name__ == '__main__':
    sys.exit(main())
