#!/usr/bin/env python

import sys
import accolite


def main(): 
    if accolite.workingdir() == "":
        sys.stderr.write("It seems that you are not in a working accolite project!\n")
        return 1
    sys.stderr.write("accolite-update not yet implemented!\n")


if __name__ == '__main__':
    sys.exit(main())
