#!/usr/bin/env python

import sys
import os.path
import shutil
import accolite

# Usage function
def usage(stream):
    stream.write("Usage: accolite-clean\n")
    

def main():
    rootdir = accolite.workingDir()
    if rootdir == "":
        sys.stderr.write("It seems that you are not in a working accolite project!\n")
        return 1
    builddir = accolite.absdir("build")
    bindir = accolite.absdir("bin")
    tmpdir = accolite.absdir("tmp")
    if os.path.isdir(builddir):
        sys.stdout.write("Deleting " + builddir + "... ");
        shutil.rmtree(builddir)
        sys.stdout.write("Done.\n");
    if os.path.isdir(bindir):
        sys.stdout.write("Deleting " + bindir + "... ");
        shutil.rmtree(bindir)
        sys.stdout.write("Done.\n");
    if os.path.isdir(tmpdir):
        sys.stdout.write("Deleting " + tmpdir + "... ");
        shutil.rmtree(tmpdir)
        sys.stdout.write("Done.\n");
    

if __name__ == "__main__":
    sys.exit(main())
