#!/usr/bin/env python

import sys
import accolite

if __name__ == '__main__':   
    if accolite.workingdir() == "":
        sys.stderr.write("It seems that you are not in a working accolite project!\n")
        exit(1)
    sys.stderr.write("accolite-update not yet implemented!\n")
