#!/usr/bin/env python
#
# Copyright (c) 2012 Casati Romain
# All rights reserved.
#
# This file is part of Accolite.
#
# Accolite is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Accolite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Accolite.  If not, see <http://www.gnu.org/licenses/>


import sys
import os
import subprocess
import accolite

# Usage function
def usage(stream):
    stream.write("Usage: accolite-init [Options] <working dir>\n")
    stream.write("Options:\n")
    stream.write("--help, -h                  : \t This help message.\n")
    stream.write("--type, -t <project type>   : \t Specify project type (\"c\" or \"cpp\").\n")
    stream.write("--config-file, -c <xml file>: \t Give a configuration file for initialize the project.\n")


def main():
    # Preset options
    configfile = ""
    projecttype = "cpp"
    # Get options
    argv = sys.argv[1:]
    while len(argv) > 0 and argv[0].startswith("-"):
        if argv[0] in ["--help","-h"]:
            usage(sys.stdout)
            return 0
        elif argv[0] in ["--type","-t"]:
            argv = argv[1:]
            projecttype = argv[0]
        elif argv[0] in ["--config-file","-c"]:
            argv = argv[1:]
            configfile = argv[0]
        else:
            sys.stderr.write("Unknown option " + argv[0] + "!")
            usage(sys.stderr)
            return 1
        # Shift argument
        argv = argv[1:]

    if len(argv) == 0:
        sys.stderr.write("Mandatory argument <working dir> not found.\n")
        usage(sys.stderr)
        return 2

    # check project type
    if projecttype != "cpp" and projecttype != "c":
        sys.stderr.write("Project type must be \"c\" or \"cpp\".\n")
        usage(sys.stderr)
        return 3

    # Set dirs
    rootdir = argv[0]
    accolitedir = os.path.abspath(os.path.join(rootdir, ".accolite"))
    if os.path.isdir(accolitedir):
        sys.stderr.write("Directory " + accolitedir + " allready exists.\n")
        return 4
    os.makedirs(accolitedir)

    # Project name
    projectname = os.path.basename(os.path.abspath(rootdir))
    # Put the config file inside .accolite
    if configfile == "":
        configxml = accolite.defaultxml(projectname, projecttype)
    else:
        configxml = parse(configfile)
    configxmlfile = open(os.path.abspath(os.path.join(accolitedir, "config.xml")), 'w')
    configxml.writexml(configxmlfile)
    configxmlfile.close()

    # Go inside working dir
    os.chdir(rootdir)

    return subprocess.call([accolite.scriptOfCommand("update")])

if __name__ == '__main__':
    sys.exit(main())
