#!/usr/bin/env python
#
# Copyright (c) 2012 Casati Romain
# All rights reserved.
#
# This file is part of Accolite.
#
# Accolite is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Accolite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Accolite.  If not, see <http://www.gnu.org/licenses/>


import sys
import accolite

# Usage function
def usage(stream):
    stream.write("Usage: accolite-bash-completion [Options]\n")
    stream.write("Options:\n")
    stream.write("--help, -h                  : \t This help message.\n")

def main():
    print "Assuming you are using bash."
    print "To enable bash completion for accolite, just create"
    print "a file named .bash_completions in your home (~/) and put"
    print "in it the folowing lines:"
    print "    if $(command -v accolite-install-dir >/dev/null 2>&1)\\"
    print "       && [ -f $(accolite-install-dir)/accolite_bash_completion ]; then"
    print "        . $(accolite-install-dir)/accolite_bash_completion"
    print "    fi"
    print "Then add at the end of your .bashrc the folowing lines:"
    print "    if [ -f ~/.bash_completions ]; then"
    print "        . ~/.bash_completions"
    print "    fi"
    print "The completion will start once .bashrc will be sourced."

if __name__ == '__main__':
    sys.exit(main())
