#!/usr/bin/env python
#
# Copyright (c) 2012 Casati Romain
# All rights reserved.
#
# This file is part of Accolite.
#
# Accolite is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Accolite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Accolite.  If not, see <http://www.gnu.org/licenses/>


import sys
import os.path
import shutil
import accolite

# Usage function
def usage(stream):
    stream.write("Usage: accolite-clean\n")
    

def main():
    rootdir = accolite.workingDir()
    if rootdir == "":
        sys.stderr.write("It seems that you are not in a working accolite project!\n")
        return 1
    builddir = accolite.absdir("build")
    bindir = accolite.absdir("bin")
    tmpdir = accolite.absdir("tmp")
    if os.path.isdir(builddir):
        sys.stdout.write("Deleting " + builddir + "... ");
        shutil.rmtree(builddir)
        sys.stdout.write("Done.\n");
    if os.path.isdir(bindir):
        sys.stdout.write("Deleting " + bindir + "... ");
        shutil.rmtree(bindir)
        sys.stdout.write("Done.\n");
    if os.path.isdir(tmpdir):
        sys.stdout.write("Deleting " + tmpdir + "... ");
        shutil.rmtree(tmpdir)
        sys.stdout.write("Done.\n");
    

if __name__ == "__main__":
    sys.exit(main())
